# Site settings
title: BioHack Academy Syllabus
email: pieter@waag.org
description: > # this means to ignore newlines until "baseurl:"
  Waag Society's Biohack Academy is an intense 10 week biohacking course held in the Amsterdam Fablab and Open Wetlab.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://biohackacademy.github.io" # the base hostname & protocol for your site
twitter_username: waag
github_username:  pietervanboheemen

# Plugins
safe: false

# Build settings
markdown: kramdown
